apiVersion: v1
kind: DeploymentConfig
metadata:
  name: fedmsg-relay
  labels:
    app: fedmsg-relay
    service: fedmsg-relay
spec:
  replicas: 1
  selector:
    deploymentconfig: fedmsg-relay
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: fedmsg-relay
        deploymentconfig: fedmsg-relay
    spec:
      containers:
      - name: fedmsg-relay
        image: fedmsg-relay:latest
        ports:
        - containerPort: 3999
        - containerPort: 9941
        resources: {}
        volumeMounts:
        - name: fedmsg-volume
          mountPath: /etc/fedmsg.d
          readOnly: true
        readinessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 5
          tcpSocket:
            port: 3999
        livenessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 30
          tcpSocket:
            port: 3999
      volumes:
      - name: fedmsg-volume
        configMap:
          name: fedmsg-configmap
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - fedmsg-relay
      from:
        kind: ImageStreamTag
        name: fedmsg-relay:latest
        namespace: {{ project_name }}
    type: ImageChange
  - type: ConfigChange
