apiVersion: v1
kind: Service
metadata:
  name: fedmsg-relay
  labels:
    app: fedmsg-relay
    service: fedmsg-relay
spec:
  ports:
    - name: inbound
      port: 3999
      targetPort: 3999
    - name: outbound
      port: 9941
      targetPort: 9941
  selector:
    deploymentconfig: fedmsg-relay
