---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: true
    ansible_connection_options: {}
lint: |
  yamllint roles/
platforms:
  - name: kind-default
    groups:
      - k8s
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
    enabled: false
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-osdk-test}
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
scenario:
  name: default
  test_sequence:
    - lint
verifier:
  name: testinfra
  lint: |
    flake8
