apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
data:
  start.sh: |-
    cat /etc/clientcert/tls.crt /etc/clientcert/tls.key >/tmp/clientcert.combined.pem
    exec /usr/bin/fedmsg-tail
  koji.conf: |-
    [koji]
    server = https://koji-hub:8443/kojihub
    weburl = https://koji-hub:8443/koji
    topurl = https://koji-hub:8443/pkgs
    authtype = ssl
    ca = /etc/cacert/cert
    serverca = /etc/cacert/cert
    cert = /tmp/clientcert.combined.pem
