apiVersion: v1
kind: DeploymentConfig
metadata:
  name: client
  labels:
    app: client
    service: client
spec:
  replicas: 1
  selector:
    deploymentconfig: client
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: client
        deploymentconfig: client
    spec:
      containers:
      - name: client
        image: client:latest
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/client
          readOnly: true
        - name: fedmsg-volume
          mountPath: /etc/fedmsg.d
          readOnly: true
        - name: cacert-volume
          mountPath: /etc/cacert
          readOnly: true
        - name: client-cert-volume
          mountPath: /etc/clientcert
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: client-configmap
      - name: fedmsg-volume
        configMap:
          name: fedmsg-configmap
      - name: cacert-volume
        secret:
          secretName: cacert
      - name: client-cert-volume
        secret:
          secretName: cert-client-admin
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - client
      from:
        kind: ImageStreamTag
        name: client:latest
        namespace: {{ project_name }}
    type: ImageChange
  - type: ConfigChange
