apiVersion: v1
kind: ConfigMap
metadata:
  name: kojira-configmap
data:
  start.sh: |-
    cat /etc/clientcert/tls.crt /etc/clientcert/tls.key >/tmp/clientcert.combined.pem
    exec /usr/sbin/kojira --fg --verbose --force-lock
  kojira.conf: |-
    [kojira]
    ; Configuration authentication
    serverca = /etc/cacert/cert
    user={{ username }}
    cert=/tmp/clientcert.combined.pem

    server=https://koji-hub:8443/kojihub
    with_src=no
    max_repo_tasks=15
    repo_tasks_limit=15
    logfile=/dev/stdout
