apiVersion: v1
kind: Route
metadata:
  name: route-mbs-frontend
spec:
{% if hostname != "" %}
  host: {{ hostname }}
{% endif %}
  to:
    kind: Service
    name: mbs-frontend
  tls:
    termination: passthrough
