apiVersion: v1
kind: Service
metadata:
  name: mbs-frontend
  labels:
    app: mbs-frontend
    service: mbs-frontend
spec:
  ports:
    - name: web
      port: 8443
      targetPort: 8443
  selector:
    deploymentconfig: mbs-frontend
