apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
data:
  POSTGRES_HOST: cG9zdGdyZXNxbA== #postgresql
  POSTGRES_DB: bWJveGRi #mboxdb
  POSTGRES_USER: a29qaQ== #koji
  POSTGRES_PASSWORD: bWJveA== #mbox
