apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: koji-builder
  name: koji-builder
spec:
  runPolicy: Serial
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: koji-builder:latest
  source:
    secrets:
    - secret:
        name: cacert
      destinationDir: cacert
    dockerfile: |-
      FROM centos:7
      COPY cacert/cert /etc/pki/ca-trust/source/anchors/mbox_ca.pem
      RUN update-ca-trust
      RUN yum install -y koji-builder
      ENTRYPOINT bash /etc/kojid/start.sh
