apiVersion: v1
kind: ConfigMap
metadata:
  name: koji-builder-configmap
data:
  start.sh: |-
    cat /etc/clientcert/tls.crt /etc/clientcert/tls.key >/tmp/clientcert.combined.pem
    exec /usr/sbin/kojid --fg --force-lock --verbose
  kojid.conf: |-
    [kojid]
    maxjobs={{ maxjobs }}
    keepalive=True
    use_createrepo_c=True
    topurl = https://koji-hub:8443/pkgs
    pkgurl = https://koji-hub:8443/pkgs
    vendor={{ vendor }}
    packager={{ vendor }}
    distribution={{ vendor }}
    mockhost=redhat-linux-gnu
    server=https://koji-hub:8443/kojihub
    build_arch_can_fail = True
    plugins=

    ; Configuration authentication
    serverca = /etc/cacert/cert
    user=koji-builder-built-in-1
    cert=/tmp/clientcert.combined.pem
