- hosts: all
  become: true
  tasks:
    - name: Add Vagrant user and home-dir
      user:
        name: vagrant
- hosts: all
  become: true
  become_method: sudo
  vars:
  roles:
    - mbbox-dev
    - openshift-osdk
- hosts: all
  tasks:
    - name: Run molecule test-cluster
      command: chdir={{ansible_user_dir}}/{{zuul.project.src_dir}}/mbox-operator molecule --debug test -s test-cluster
      become: true
