apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mntkoji
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{% if volumename != "" %}
  volumeName: "{{ volumename }}"
{% endif %}
