apiVersion: v1
kind: Route
metadata:
  name: route-koji-hub
spec:
{% if hostname != "" %}
  host: {{ hostname }}
{% endif %}
  to:
    kind: Service
    name: koji-hub
  tls:
    termination: passthrough
