apiVersion: v1
kind: Service
metadata:
  name: koji-hub
  labels:
    app: koji-hub
    service: koji-hub
spec:
  ports:
    - name: web
      port: 8443
      targetPort: 8443
  selector:
    deploymentconfig: koji-hub
