apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mbs-backend
  labels:
    app: mbs-backend
    service: mbs-backend
spec:
  replicas: {{ replicas }}
  selector:
    deploymentconfig: mbs-backend
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: mbs-backend
        deploymentconfig: mbs-backend
    spec:
      containers:
      - name: mbs-backend
        image: mbs-backend:latest
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/module-build-service
          readOnly: true
        - name: backend-config-volume
          mountPath: /etc/mbs-backend
          readOnly: true
        - name: fedmsg-volume
          mountPath: /etc/fedmsg.d
          readOnly: true
        - name: cacert-volume
          mountPath: /etc/cacert
          readOnly: true
        - name: client-cert-volume
          mountPath: /etc/clientcert
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: mbs-configmap
      - name: backend-config-volume
        configMap:
          name: mbs-backend-configmap
      - name: fedmsg-volume
        configMap:
          name: fedmsg-configmap
      - name: cacert-volume
        secret:
          secretName: cacert
      - name: client-cert-volume
        secret:
          secretName: cert-client-mbs-backend
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mbs-backend
      from:
        kind: ImageStreamTag
        name: mbs-backend:latest
        namespace: {{ project_name }}
    type: ImageChange
  - type: ConfigChange
